// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBsJMiDo3AUSZZmxYKkbkFqj3001tVbRs',
    appId: '1:505495639475:web:aedb0f030409ec5c5927c6',
    messagingSenderId: '505495639475',
    projectId: 'practice-app-6b018',
    authDomain: 'practice-app-6b018.firebaseapp.com',
    storageBucket: 'practice-app-6b018.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLYWv-PKnwhujFOKQ1hv_XvJoyDa6kLwE',
    appId: '1:505495639475:android:96e6dacade51e2195927c6',
    messagingSenderId: '505495639475',
    projectId: 'practice-app-6b018',
    storageBucket: 'practice-app-6b018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNmOs_TrOrnB0SgRr7IrYaCb8ARzUMfQ',
    appId: '1:505495639475:ios:778a700550b5cae85927c6',
    messagingSenderId: '505495639475',
    projectId: 'practice-app-6b018',
    storageBucket: 'practice-app-6b018.appspot.com',
    iosClientId: '505495639475-om7ts5e1iopfjo83v3g2ao2tfer3m4vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUNmOs_TrOrnB0SgRr7IrYaCb8ARzUMfQ',
    appId: '1:505495639475:ios:a05ae789e0f4a0e95927c6',
    messagingSenderId: '505495639475',
    projectId: 'practice-app-6b018',
    storageBucket: 'practice-app-6b018.appspot.com',
    iosClientId: '505495639475-tvkckqkts6qctp5pp6sgrsdisqvkfq3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceApp.RunnerTests',
  );
}
